// <auto-generated />
namespace DiamondQuranWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addTafsirs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTafsirs));
        
        string IMigrationMetadata.Id
        {
            get { return "202007270451015_addTafsirs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
