//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondQuranWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiamondQuranWeb.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Verses Added.
        /// </summary>
        public static string AllVersesAdded {
            get {
                return ResourceManager.GetString("AllVersesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Verses on search result will be adeed.
        /// </summary>
        public static string AllWillBeAdded {
            get {
                return ResourceManager.GetString("AllWillBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tafsir Already Installed.
        /// </summary>
        public static string AlreadyInstalled {
            get {
                return ResourceManager.GetString("AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And Not.
        /// </summary>
        public static string AndNot {
            get {
                return ResourceManager.GetString("AndNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Font Size.
        /// </summary>
        public static string ArabicFontSize {
            get {
                return ResourceManager.GetString("ArabicFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Font Style.
        /// </summary>
        public static string ArabicFontStyle {
            get {
                return ResourceManager.GetString("ArabicFontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Tafsir File From The Server?.
        /// </summary>
        public static string AskToDownload {
            get {
                return ResourceManager.GetString("AskToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse added.
        /// </summary>
        public static string AyaAdded {
            get {
                return ResourceManager.GetString("AyaAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse.
        /// </summary>
        public static string Ayah {
            get {
                return ResourceManager.GetString("Ayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayah Number.
        /// </summary>
        public static string AyahNumber {
            get {
                return ResourceManager.GetString("AyahNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayah Source.
        /// </summary>
        public static string AyahSrc {
            get {
                return ResourceManager.GetString("AyahSrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verses.
        /// </summary>
        public static string AyaMany {
            get {
                return ResourceManager.GetString("AyaMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayat Tafsirs.
        /// </summary>
        public static string AyatTafsirs {
            get {
                return ResourceManager.GetString("AyatTafsirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters Numbers.
        /// </summary>
        public static string CharactersNumbers {
            get {
                return ResourceManager.GetString("CharactersNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Added.
        /// </summary>
        public static string CommentAdded {
            get {
                return ResourceManager.GetString("CommentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment has been deleted.
        /// </summary>
        public static string CommentDel {
            get {
                return ResourceManager.GetString("CommentDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains A.
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains Letters (Arranged).
        /// </summary>
        public static string ContainsLettersArranged {
            get {
                return ResourceManager.GetString("ContainsLettersArranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains Letters (Un Arranged).
        /// </summary>
        public static string ContainsLettersUnArranged {
            get {
                return ResourceManager.GetString("ContainsLettersUnArranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains (Noncontiguous).
        /// </summary>
        public static string ContainsNoncontiguous {
            get {
                return ResourceManager.GetString("ContainsNoncontiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayah Has been copied to clipboard.
        /// </summary>
        public static string CopyClipboard {
            get {
                return ResourceManager.GetString("CopyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayah Has been deleted from clipboard.
        /// </summary>
        public static string DelClipboard {
            get {
                return ResourceManager.GetString("DelClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond Quran.
        /// </summary>
        public static string DiamondQuran {
            get {
                return ResourceManager.GetString("DiamondQuran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesnt Exist.
        /// </summary>
        public static string DoesntExist {
            get {
                return ResourceManager.GetString("DoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Done.
        /// </summary>
        public static string DoneDel {
            get {
                return ResourceManager.GetString("DoneDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Completed.
        /// </summary>
        public static string DownloadCompleted {
            get {
                return ResourceManager.GetString("DownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pls enter a list name.
        /// </summary>
        public static string EnterAlistName {
            get {
                return ResourceManager.GetString("EnterAlistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pls enter more than two letters.
        /// </summary>
        public static string EnterMoreLetters {
            get {
                return ResourceManager.GetString("EnterMoreLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite List.
        /// </summary>
        public static string Fav {
            get {
                return ResourceManager.GetString("Fav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First In Ayah (Contains).
        /// </summary>
        public static string FirstInAyahContains {
            get {
                return ResourceManager.GetString("FirstInAyahContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First In Surah (Contains).
        /// </summary>
        public static string FirstInSurahContains {
            get {
                return ResourceManager.GetString("FirstInSurahContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First In Word.
        /// </summary>
        public static string FirstInWord {
            get {
                return ResourceManager.GetString("FirstInWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        public static string Fonts {
            get {
                return ResourceManager.GetString("Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string HowMany {
            get {
                return ResourceManager.GetString("HowMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Changed Successfully.
        /// </summary>
        public static string LangChanged {
            get {
                return ResourceManager.GetString("LangChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last In Ayah (Contains).
        /// </summary>
        public static string LastInAyahContains {
            get {
                return ResourceManager.GetString("LastInAyahContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last In Surah (Contains).
        /// </summary>
        public static string LastInSurahContains {
            get {
                return ResourceManager.GetString("LastInSurahContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last In Word.
        /// </summary>
        public static string LastInWord {
            get {
                return ResourceManager.GetString("LastInWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Added.
        /// </summary>
        public static string ListAdded {
            get {
                return ResourceManager.GetString("ListAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic Search (And).
        /// </summary>
        public static string LogicSearchAnd {
            get {
                return ResourceManager.GetString("LogicSearchAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic Search (Not).
        /// </summary>
        public static string LogicSearchNot {
            get {
                return ResourceManager.GetString("LogicSearchNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic Search (Or).
        /// </summary>
        public static string LogicSearchOr {
            get {
                return ResourceManager.GetString("LogicSearchOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logics Search.
        /// </summary>
        public static string LogicsSearch {
            get {
                return ResourceManager.GetString("LogicsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest Ayah.
        /// </summary>
        public static string LongestAyah {
            get {
                return ResourceManager.GetString("LongestAyah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest Surah.
        /// </summary>
        public static string LongestSurah {
            get {
                return ResourceManager.GetString("LongestSurah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest Words.
        /// </summary>
        public static string LongestWords {
            get {
                return ResourceManager.GetString("LongestWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches (Noncontiguous).
        /// </summary>
        public static string MatchesNoncontiguous {
            get {
                return ResourceManager.GetString("MatchesNoncontiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Words.
        /// </summary>
        public static string MostWords {
            get {
                return ResourceManager.GetString("MostWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Copies To Clipboard.
        /// </summary>
        public static string MultipleCopiesClipboard {
            get {
                return ResourceManager.GetString("MultipleCopiesClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all Verses In The Clipboard.
        /// </summary>
        public static string MultipleDelClipboard {
            get {
                return ResourceManager.GetString("MultipleDelClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Search.
        /// </summary>
        public static string MultipleSearch {
            get {
                return ResourceManager.GetString("MultipleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Exist ... Pls Choice Another Name.
        /// </summary>
        public static string NameExist {
            get {
                return ResourceManager.GetString("NameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains These Letters.
        /// </summary>
        public static string NotExcept {
            get {
                return ResourceManager.GetString("NotExcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , The Tafsir file Doesnt Exist in The Server at the Momment.
        /// </summary>
        public static string NotExistOnServer {
            get {
                return ResourceManager.GetString("NotExistOnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Installed.
        /// </summary>
        public static string NotInstalled {
            get {
                return ResourceManager.GetString("NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Repetition.
        /// </summary>
        public static string NumberOfRepetition {
            get {
                return ResourceManager.GetString("NumberOfRepetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quranic Statistics.
        /// </summary>
        public static string QuranicStatistics {
            get {
                return ResourceManager.GetString("QuranicStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read The Quran.
        /// </summary>
        public static string ReadQuran {
            get {
                return ResourceManager.GetString("ReadQuran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Search.
        /// </summary>
        public static string ReverseSearch {
            get {
                return ResourceManager.GetString("ReverseSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string SearchMatches {
            get {
                return ResourceManager.GetString("SearchMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Option.
        /// </summary>
        public static string SearchOption {
            get {
                return ResourceManager.GetString("SearchOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pls Select a Search Option.
        /// </summary>
        public static string SelectSearchOption {
            get {
                return ResourceManager.GetString("SelectSearchOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seperated Search.
        /// </summary>
        public static string SeperatedSearch {
            get {
                return ResourceManager.GetString("SeperatedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surah.
        /// </summary>
        public static string Surah {
            get {
                return ResourceManager.GetString("Surah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tafsirs.
        /// </summary>
        public static string Tafsirs {
            get {
                return ResourceManager.GetString("Tafsirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pls enter more than two letters And select A search Option.
        /// </summary>
        public static string TwoSrchBoxesMissing {
            get {
                return ResourceManager.GetString("TwoSrchBoxesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select A Verse.
        /// </summary>
        public static string VerseSelect {
            get {
                return ResourceManager.GetString("VerseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Within Search.
        /// </summary>
        public static string WithinSearch {
            get {
                return ResourceManager.GetString("WithinSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write A Comment.
        /// </summary>
        public static string WriteAcomment {
            get {
                return ResourceManager.GetString("WriteAcomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Question Or Suggestion Are welcome.
        /// </summary>
        public static string WriteUs {
            get {
                return ResourceManager.GetString("WriteUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong.
        /// </summary>
        public static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Words.
        /// </summary>
        public static string Wsearch {
            get {
                return ResourceManager.GetString("Wsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
